### ISSUE TITLE
Error compilation on 14.04

### ISSUE THREAD

**Issue by nikkolasg** [dfinity/bn#10]
Hi there, 

I'm trying to compile on 14.04 and I have this error:
```
root@e88509964d08:/bn# make
make -C mcl UPDATE_ASM=1 lib/libmcl.a CFLAGS_USER=-std=c++11 MCL_MAX_BIT_SIZE=384
make[1]: Entering directory `/bn/mcl'
g++ -o src/gen src/gen.cpp -g3 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith -m64 -I include -I test -I ../xbyak -I ../cybozulib/include -std=c++11 -fomit-frame-pointer -DNDEBUG -Ofast -march=native -fPIC -DMCL_MAX_BIT_SIZE=384 -DMCL_USE_LLVM=1 -O0
src/gen -f src/func.list > src/base64.ll
opt -O3 -o - src/base64.ll -march=x86-64 | llc -O3 -o src/asm/x86-64.s -march=x86-64 -relocation-model=pic  -pre-RA-sched=list-ilp -max-sched-reorder=128
opt: src/base64.ll:16:24: error: expected value token
%r5 = getelementptr i64, i64* %r2, i64 %r4
                       ^
```
Apparently it does not affect the overall compilation process because it finishes and procudes the library but still, it seems something to solve ;)

**Comment by nikkolasg** [comment]
Another error I don't know how to solve is the following:
```
/usr/local/lib/libbls384.so: undefined reference to `mcl_fp_add1L'
....
```
I can't get any references to the mcl library although:
- `libbls384.so` is recognized
- `libmcl.a` is in the same place as `libbls384.so`

I'm not a C/C++ guru, so do you have any idea how to solve that ? I don't know how I made it work on Archlinux but it worked.
Seems like the linked (`ld`) is not recognizing the `libmcl.a` library...

**Comment by nikkolasg** [comment]
Both errors are clearly related I would say. From what I gather, in the compilation phase, `libmcl` should be statically linked. It is not currently, and the compilation error should be the root cause...

**Comment by nikkolasg** [comment]
I have tried many different compilers, can you provide me with the versions you use ? (llvm, clang, llvm-g++ etc ?)

**Comment by herumi** [comment]
I'll check it, so please could you wait a moment.

**Comment by nikkolasg** [comment]
Ok I made it work in 14.04. I had to install the llvm-3.8 at least, doing the symbolic linking myself for opt and llc and then it worked. I'm doing a Dockerfile, and will write down the steps to make it work ... Oo

Is there a reason why it can not be compiled with 3.7 ? Would it be complicated to make it work ? Just asking in the wild, because it's quite a hurdle to install a newer version than what's avaiable on Ubuntu.

**Comment by nikkolasg** [comment]
OK I made it work for Travis after I saw your .travis.yml. I had a very hard time but it is now functional. Thanks anyway and sorry for the trouble ;)

**Comment by nikkolasg** [comment]
But an ubuntu package would be really neat to avoid all this trickery ^^

**Comment by timohanke** [comment]
Yes, any kind of packages would be awesome, debian or ubuntu.

**Comment by herumi** [comment]
@nikkolasg
I confirmed that the following commands run well on Ubuntu 14.04.5 LTS.
Could you try it?

```
sudo apt install llvm-3.9 g++ libgmp-dev libssl-dev
git clone git@github.com:dfinity/bn
cd bn
sudo make LLVM_VER=-3.9 install
```

**Comment by herumi** [comment]
If you want to use llvm-3.8, then type

```
make LLVM_VER=-3.8
```

**Comment by herumi** [comment]
>Is there a reason why it can not be compiled with 3.4 (default version on 14.04) ? Would it be complicated to make it work ? Just asking in the wild, because it's quite a hurdle to install a newer version than what's avaiable on Ubuntu.

The cause is due to the boring LLVM syntax incompatibility between 3.4 and the later version.

```
%r6 = load i64* %r5          ; ok on llvm-3.4, err on llvm-3.5
%r6 = load i64, i64* %r5   ; err on llvm-3.4, ok on llvm-3.5
```

If you add `-old` option to $(GEN_EXE) in bn/mcl/Makefile as the following if you want to use llvm-3.4.
```
// l.117
$(LLVM_SRC): $(GEN_EXE) $(FUNC_LIST)
        $(GEN_EXE) -old -f $(FUNC_LIST) > $@

// l.126
src/base$(BIT).bmi2.ll: $(GEN_EXE)
        $(GEN_EXE) -old -f $(FUNC_LIST) -s bmi2 > $@
```

I added src/asm/*.s to avoid the trouble for `herumi/mcl`(mcl does not require llvm), but I was told to get rid of them in `bn` and I checked it on only Ubuntu 16, I'm sorry.

**Comment by herumi** [comment]
I fixed [Makefile](https://github.com/dfinity/bn/commit/1d0f9cc35ce8093277bc054b57a0e1db9b956feb).
