### ISSUE TITLE
Cannot compile on Darwin 16.7.0

### ISSUE THREAD

**Issue by enzoh** [dfinity/bn#4]
Undefined symbols for architecture x86_64:
  "operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, __mpz_struct const*)", referenced from:
      cybozu::Exception& cybozu::Exception::operator<<<__gmp_expr<__mpz_struct [1], __mpz_struct [1]> >(__gmp_expr<__mpz_struct [1], __mpz_struct [1]> const&) in bls_c-cfa013.o
      cybozu::Exception& cybozu::Exception::operator<<<__gmp_expr<__mpz_struct [1], __mpz_struct [1]> >(__gmp_expr<__mpz_struct [1], __mpz_struct [1]> const&) in libmcl.a(fp.o)
ld: symbol(s) not found for architecture x86_64

**Comment by enzoh** [comment]
I am able to compile MCL without issue, but BLS fails with the error above.

**Comment by enzoh** [comment]
Setting CFLAGS=-lgmpxx fixes this issue.

**Comment by herumi** [comment]
I noticed the problem a little before. I do not understand why the option is necessary to make a shared library, but I'll fix it later.

**Comment by herumi** [comment]
I fixed it.
https://github.com/dfinity/bn/commit/4ddb2075d962da05f2996bdd65eac8634e493006
